### ISSUE TITLE
Edit\Claim the listing

### ISSUE THREAD

**Issue by snigdharbs** [so-ale/Bir-United#11]
Is there a way we can get access to edit the existing listings? 
For instance can I get an access to edit the listing done others? 

Some informations for the existing listing needs to be edited. 
Also, by when can the owners claim their listing and edit the same?

**Comment by ibn-ju** [comment]
@snigdharbs you can login via www.birunited.com/wp-admin and then go to citybook listings to make changes. Call me if you face any issues. (You're already an admin on the site)

**Comment by so-ale** [comment]
I'm working on an easier option to do this. Until then, we can manually transfer their listing to their user account from wp-admin.

**Comment by so-ale** [comment]
Work in progress, still. This should be ready in 2-3 days.

**Comment by so-ale** [comment]
This has been fixed. Will give a demo over next call.
