### ISSUE TITLE
Guide listing

### ISSUE THREAD

**Issue by snigdharbs** [so-ale/Bir-United#12]
Spoke to a couple of local guides and briefed them about the website . 
They were keen on being listed. However , under which section do I list them as of now?

**Comment by so-ale** [comment]
I have created a category named "Hiking & Trekking". They can be added here, maybe?

**Comment by snigdharbs** [comment]
Alright.

**Comment by so-ale** [comment]
"Hiking & Trekking" subcategory added. All listings for guides can be added here. Thanks.
