### ISSUE TITLE
Urgent Additions

### ISSUE THREAD

**Issue by ibn-ju** [so-ale/Bir-United#13]
Sohail, 

add the about page on the header (text already sent) 
add the 'trekking' category to the homepage
In 'activities' category while adding a listing, add one category - trekking (right now, only paragliding is there)

**Comment by so-ale** [comment]
https://birunited.com/about-bir/

Feedback welcome

**Comment by so-ale** [comment]
"About Bir" page has been added.

"Hiking and Trekking" sub-category added under "Activities" category. Same has been put on the homepage.

**Comment by ibn-ju** [comment]
About Bir should also be visible somewhere on the home page.
