### ISSUE TITLE
Fix Mobile Header Navigation

### ISSUE THREAD

**Issue by so-ale** [so-ale/Bir-United#2]
There is an overlap of elements in the header when viewed on a mobile device. 

> Try either making the user panel button invisible, or make the nav button small enough to fit. Another option is to disable the Search bar.

**Comment by so-ale** [comment]
Fixed. 

@ibn-ju Can you verify?

**Comment by ibn-ju** [comment]
This is how it is looking on mobile

**Comment by so-ale** [comment]
This issue has been confirmed fixed.
