### ISSUE TITLE
Fix overlaping navigation items in the header

### ISSUE THREAD

**Issue by so-ale** [so-ale/Bir-United#3]
On some devices with smaller screen resolution (eg: @ibn-ju 's laptop), navigation elements are overlapping with other header elements.

**Comment by ibn-ju** [comment]
works well on my system now

**Comment by snigdharbs** [comment]
Still facing this issue when accessing the website on an ipad

**Comment by so-ale** [comment]
This looks fixed to me. 
@ibn-ju and @snigdharbs Can you verify?
Thanks!

**Comment by snigdharbs** [comment]
Not fixed yet. Just checked.

**Comment by so-ale** [comment]
Hi @snigdharbs 
Possible for you to send me a screenshot at lalani[dot]sohail[at]gmail[dot]com?
Thanks.

**Comment by so-ale** [comment]
Fixed
