### ISSUE TITLE
Social Media Login Integration

### ISSUE THREAD

**Issue by so-ale** [so-ale/Bir-United#7]
Login to BirUnited using facebook and/or google

@ibn-ju @xoxobir good idea?

**Comment by ibn-ju** [comment]
yes! facebook and google

**Comment by so-ale** [comment]
Okay. Do we have a dummy facebook profile/account by any chance? I will need access to one to integrate facebook. 

If not, I will create one.

**Comment by xoxobir** [comment]
I just made you the admin for Bir United @ibn-ju 
Sohail Please send me friend request https://www.facebook.com/rana.ankush9

**Comment by so-ale** [comment]
Social login has been integrated with Facebook, Google, and GitHub. I have tested it with Github and works fine. Can someone test it with Facebook and Google?

Test on-
- [ ] Facebook
- [ ] Google
- [ ] GitHub

**Comment by so-ale** [comment]
Social Media Login integration complete.

**Comment by so-ale** [comment]
*Instagram* added
